spring:
  application:
    name: handleGOD

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWD}
    username: ${DATABASE_USERNAME}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.boot.actuate: DEBUG
    com.handleGod: DEBUG

server:
  port: 12347