spring:
  application:
    name: cacophony
  config:
    import: classpath:application-dev.yml

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  datasource:
    name: cacophony
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/cacophony
    driver-class-name: org.postgresql.Driver

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
#    elasticsearch:
#      repositories:
#        enabled: true

  # TODO SECRETS
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: PLACEHOLDER
            client-secret: PLACEHOLDER
            scope:
              - email
              - profile
          github:
            client-id: PLACEHOLDER
            client-secret: PLACEHOLDER
            scope:
              - email
              - profile
#    user:
#      name: admin
#      password: admin

app:
  pepper: ${APP_PEPPER}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    refresh-expiration-time: 900000 # 15 min
    access-expiration-time: 604800000 # 7 days

server:
  port: 8080