spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path:/api/v1/users/**
        - id: auction-service
          uri: lb:http://AUCTION-SERVICE
          predicates:
            - Path:/api/v1/auctions/**
        - id: bid-service
          uri: lb:http://BID-SERVICE
          predicates:
            - Path:/api/v1/bids/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path:/api/v1/products/**
server:
  port: 8222
