spring:
  config:
    import: classpath:application-dev.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}
    driver-class-name: org.postgresql.Driver

 kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: bid-group, auction-group, product-group, user-group
      
  mail:
    host: smtp.gmail.com
    username: ${smtp.username}
    password: ${smtp.password}
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8050
