spring:
  application:
    name: event-horizon
  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: ${dev.db.username}
    password: ${dev.db.password}
    url: ${dev.db.url}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080