spring:
  application:
    name: NWeb-scrapper
  config:
    import: optional:application.yml

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    username: jrr
    url: jdbc:postgresql://localhost:5432/nwebscrapper

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: webscrapper-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8080