spring:
  application:
    name: inventory-management

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      database: 0
      host: localhost
      port: 6379


server:
  port: 8080