services:
  redis:
    image: redis:7.2-alpine
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cacophony_network
#    environment:
#      REDIS_PASSWORD: admin
    command: redis-server # --requirepass $REDIS_PASSWORD

#  postgres:
#    image: postgres:15.13
#    container_name: psql_container
#    ports:
#      - "5432:5432"
#    volumes:
#      - psql_dat:/data
#    networks:
#      - cacophony_network
#    environment:
#      POSTGRES_DB: cacophony
#      POSTGRES_USER: jrr
#      POSTGRES_PASSWORD: admin
#      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  redis_data:
  psql_data:

networks:
  cacophony_network:
    driver: bridge